#!/usr/bin/env python3
"""Generate the runtime Swift postcard text library from author markdown files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO_ROOT / "Content" / "AnimalDatabase" / "PostcardTextLibrary_1.0.6"
OUTPUT_FILE = REPO_ROOT / "TripPet" / "Domain" / "Services" / "PostcardTextLibrary.swift"

SOURCE_FILES = [
    ("xiaoman_hamster", "仓鼠小满明信片人格与状态文本合集.md"),
    ("tangyuan_puppy", "小狗糖圆明信片人格与状态文本合集.md"),
    ("moji_cat", "小猫墨迹明信片人格与状态文本合集.md"),
    ("dengdeng_rabbit", "兔子灯灯明信片人格与状态文本合集.md"),
    ("feifei_parrot", "鹦鹉飞飞明信片人格与状态文本合集.md"),
    ("xiaolu_guinea_pig", "豚鼠小炉明信片人格与状态文本合集.md"),
    ("deer_visitor", "小鹿啾啾明信片人格与状态文本合集.md"),
    ("fox_visitor", "小狐狸埃尼明信片人格与状态文本合集.md"),
    ("bear_visitor", "小熊墩墩明信片人格与状态文本合集.md"),
]


def parse_markdown_narratives(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    narratives: list[str] = []
    in_text_section = False
    index = 0

    while index < len(lines):
        line = lines[index].strip()
        if line.startswith("## "):
            in_text_section = "｜10条" in line
            index += 1
            continue

        if in_text_section and re.fullmatch(r"\d+\.\s*", line):
            index += 1
            body_lines: list[str] = []
            while index < len(lines):
                candidate = lines[index].strip()
                if (
                    re.fullmatch(r"\d+\.\s*", candidate)
                    or candidate.startswith("## ")
                    or candidate == "---"
                ):
                    break
                if candidate:
                    body_lines.append(candidate)
                index += 1
            body = "\n".join(body_lines).strip()
            if body:
                narratives.append(body)
            continue

        index += 1

    return narratives


def swift_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\n", "\\n")
    )


def make_entry(identifier: str, animal_key: str, body: str) -> str:
    return (
        f'        PostcardNarrative(id: "{identifier}", '
        f'animalKey: "{animal_key}", '
        f'body: "{swift_string(body)}")'
    )


def build_swift(entries: list[tuple[str, str, str]]) -> str:
    entry_lines = [make_entry(identifier, animal_key, body) for identifier, animal_key, body in entries]
    joined_entries = ",\n".join(entry_lines)
    return f"""import Foundation

struct PostcardNarrative: Equatable {{
    let id: String
    let animalKey: String
    let body: String
}}

enum PostcardTextLibrary {{
    static func randomEntry(for animal: Animal, excluding consumedIds: Set<String>) -> PostcardNarrative? {{
        let key = animalKey(for: animal)
        let available = narratives.filter {{ $0.animalKey == key && consumedIds.contains($0.id) == false }}
        return available.randomElement()
    }}

    static func animalKey(for animal: Animal) -> String {{
        if animal.id == "xiaoman_hamster" || animal.homeAssetName.contains("xiaoman_hamster") {{
            return "xiaoman_hamster"
        }}
        if animal.id == "tangyuan_puppy" || animal.homeAssetName.contains("tangyuan_puppy") {{
            return "tangyuan_puppy"
        }}
        if animal.id == "moji_cat" || animal.homeAssetName.contains("moji_cat") {{
            return "moji_cat"
        }}
        if animal.id == "dengdeng_rabbit" || animal.homeAssetName.contains("dengdeng_rabbit") {{
            return "dengdeng_rabbit"
        }}
        if animal.id == "feifei_parrot" || animal.homeAssetName.contains("feifei_parrot") {{
            return "feifei_parrot"
        }}
        if animal.id == "xiaolu_guinea_pig" || animal.homeAssetName.contains("xiaolu_guinea_pig") {{
            return "xiaolu_guinea_pig"
        }}
        if animal.id == "deer_visitor" ||
            animal.homeAssetName.contains("deer_visitor") ||
            animal.homeAssetName.contains("jiujiu_deer") {{
            return "deer_visitor"
        }}
        if animal.id == "fox_visitor" ||
            animal.homeAssetName.contains("fox_visitor") ||
            animal.homeAssetName.contains("aini_fox") {{
            return "fox_visitor"
        }}
        if animal.id == "bear_visitor" ||
            animal.homeAssetName.contains("bear_visitor") ||
            animal.homeAssetName.contains("dundun_bear") {{
            return "bear_visitor"
        }}
        return animal.id
    }}

    // Generated by Tools/generate_postcard_text_library.py from Content/AnimalDatabase/PostcardTextLibrary_1.0.6.
    static let narratives: [PostcardNarrative] = [
{joined_entries}
    ]
}}
"""


def collect_entries() -> list[tuple[str, str, str]]:
    entries: list[tuple[str, str, str]] = []
    for animal_key, filename in SOURCE_FILES:
        path = SOURCE_DIR / filename
        narratives = parse_markdown_narratives(path)
        if not narratives:
            raise ValueError(f"No narratives parsed from {path}")
        for offset, body in enumerate(narratives, start=1):
            identifier = f"{animal_key}_textlib106_{offset:03d}"
            entries.append((identifier, animal_key, body))

    return entries


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Validate generated output without writing.")
    args = parser.parse_args()

    entries = collect_entries()
    swift = build_swift(entries)

    if args.check:
        current = OUTPUT_FILE.read_text(encoding="utf-8")
        if current != swift:
            raise SystemExit("PostcardTextLibrary.swift is out of date. Run Tools/generate_postcard_text_library.py.")
    else:
        OUTPUT_FILE.write_text(swift, encoding="utf-8")

    counts: dict[str, int] = {}
    for _, animal_key, _ in entries:
        counts[animal_key] = counts.get(animal_key, 0) + 1
    for animal_key in sorted(counts):
        print(f"{animal_key}: {counts[animal_key]}")
    print(f"total: {len(entries)}")


if __name__ == "__main__":
    main()
